# Stubs for django.contrib.flatpages.admin (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import admin
from django.utils.translation import ugettext_lazy as _

class FlatPageAdmin(admin.ModelAdmin):
    form = ...  # type: Any
    fieldsets = ...  # type: Any
    list_display = ...  # type: Any
    list_filter = ...  # type: Any
    search_fields = ...  # type: Any
