# Stubs for django.contrib.flatpages.forms (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import forms
from django.utils.translation import ugettext_lazy as _

class FlatpageForm(forms.ModelForm):
    url = ...  # type: Any
    class Meta:
        model = ...  # type: Any
        fields = ...  # type: str
    def clean_url(self): ...
    def clean(self): ...
