# Stubs for django.contrib.flatpages.middleware (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class FlatpageFallbackMiddleware:
    def process_response(self, request, response): ...
