# Stubs for django.contrib.flatpages.views (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

DEFAULT_TEMPLATE = ...  # type: str

def flatpage(request, url): ...
def render_flatpage(request, f): ...
