# Stubs for django.contrib.redirects.admin (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import admin

class RedirectAdmin(admin.ModelAdmin):
    list_display = ...  # type: Any
    list_filter = ...  # type: Any
    search_fields = ...  # type: Any
    radio_fields = ...  # type: Any
