# Stubs for django.contrib.redirects.middleware (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class RedirectFallbackMiddleware:
    response_gone_class = ...  # type: Any
    response_redirect_class = ...  # type: Any
    def __init__(self) -> None: ...
    def process_response(self, request, response): ...
