# Stubs for django.contrib.redirects.models (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import models
from django.utils.translation import ugettext_lazy as _

class Redirect(models.Model):
    site = ...  # type: Any
    old_path = ...  # type: Any
    new_path = ...  # type: Any
    class Meta:
        verbose_name = ...  # type: Any
        verbose_name_plural = ...  # type: Any
        db_table = ...  # type: str
        unique_together = ...  # type: Any
        ordering = ...  # type: Any
