# Stubs for django.contrib.postgres.fields.hstore (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.db.models import Field, Transform
from django.utils.translation import ugettext_lazy as _

class HStoreField(Field):
    empty_strings_allowed = ...  # type: bool
    description = ...  # type: Any
    default_error_messages = ...  # type: Any
    def db_type(self, connection): ...
    def get_transform(self, name): ...
    def validate(self, value, model_instance): ...
    def to_python(self, value): ...
    def value_to_string(self, obj): ...
    def formfield(self, **kwargs): ...

class KeyTransform(Transform):
    output_field = ...  # type: Any
    key_name = ...  # type: Any
    def __init__(self, key_name, *args, **kwargs) -> None: ...
    def as_sql(self, compiler, connection): ...

class KeyTransformFactory:
    key_name = ...  # type: Any
    def __init__(self, key_name) -> None: ...
    def __call__(self, *args, **kwargs): ...

class KeysTransform(Transform):
    lookup_name = ...  # type: str
    function = ...  # type: str
    output_field = ...  # type: Any

class ValuesTransform(Transform):
    lookup_name = ...  # type: str
    function = ...  # type: str
    output_field = ...  # type: Any
