# Stubs for django.contrib.postgres.fields.utils (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class AttributeSetter:
    def __init__(self, name, value) -> None: ...
