# Stubs for django.contrib.sites.admin (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import admin

class SiteAdmin(admin.ModelAdmin):
    list_display = ...  # type: Any
    search_fields = ...  # type: Any
