# Stubs for django.contrib.admin.models (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import models
from django.utils.translation import ugettext_lazy as _

ADDITION = ...  # type: int
CHANGE = ...  # type: int
DELETION = ...  # type: int

class LogEntryManager(models.Manager):
    use_in_migrations = ...  # type: bool
    def log_action(self, user_id, content_type_id, object_id, object_repr, action_flag, change_message: str = ...): ...

class LogEntry(models.Model):
    action_time = ...  # type: Any
    user = ...  # type: Any
    content_type = ...  # type: Any
    object_id = ...  # type: Any
    object_repr = ...  # type: Any
    action_flag = ...  # type: Any
    change_message = ...  # type: Any
    objects = ...  # type: Any
    class Meta:
        verbose_name = ...  # type: Any
        verbose_name_plural = ...  # type: Any
        db_table = ...  # type: str
        ordering = ...  # type: Any
    def is_addition(self): ...
    def is_change(self): ...
    def is_deletion(self): ...
    def get_edited_object(self): ...
    def get_admin_url(self): ...
