# Stubs for django.contrib.gis.db.backends.mysql.base (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.db.backends.mysql.base import DatabaseWrapper as MySQLDatabaseWrapper
from .features import DatabaseFeatures as DatabaseFeatures
from .introspection import MySQLIntrospection as MySQLIntrospection
from .operations import MySQLOperations as MySQLOperations
from .schema import MySQLGISSchemaEditor as MySQLGISSchemaEditor

class DatabaseWrapper(MySQLDatabaseWrapper):
    SchemaEditorClass = ...  # type: Any
    features = ...  # type: Any
    ops = ...  # type: Any
    introspection = ...  # type: Any
    def __init__(self, *args, **kwargs) -> None: ...
