# Stubs for django.contrib.gis.db.backends.mysql.features (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.contrib.gis.db.backends.base.features import BaseSpatialFeatures
from django.db.backends.mysql.features import DatabaseFeatures as MySQLDatabaseFeatures

class DatabaseFeatures(BaseSpatialFeatures, MySQLDatabaseFeatures):
    has_spatialrefsys_table = ...  # type: bool
    supports_add_srs_entry = ...  # type: bool
    supports_distance_geodetic = ...  # type: bool
    supports_length_geodetic = ...  # type: bool
    supports_distances_lookups = ...  # type: bool
    supports_transform = ...  # type: bool
    supports_real_shape_operations = ...  # type: bool
    supports_null_geometries = ...  # type: bool
    supports_num_points_poly = ...  # type: bool
