# Stubs for django.contrib.gis.db.backends.mysql.introspection (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.db.backends.mysql.introspection import DatabaseIntrospection

class MySQLIntrospection(DatabaseIntrospection):
    data_types_reverse = ...  # type: Any
    def get_geometry_type(self, table_name, geo_col): ...
    def supports_spatial_index(self, cursor, table_name): ...
