# Stubs for django.contrib.gis.db.backends.mysql.operations (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.contrib.gis.db.backends.base.operations import BaseSpatialOperations
from django.db.backends.mysql.operations import DatabaseOperations

class MySQLOperations(BaseSpatialOperations, DatabaseOperations):
    mysql = ...  # type: bool
    name = ...  # type: str
    select = ...  # type: str
    from_wkb = ...  # type: str
    from_text = ...  # type: str
    Adapter = ...  # type: Any
    Adaptor = ...  # type: Any
    gis_operators = ...  # type: Any
    function_names = ...  # type: Any
    disallowed_aggregates = ...  # type: Any
    def unsupported_functions(self): ...
    def geo_db_type(self, f): ...
    def get_geom_placeholder(self, f, value, compiler): ...
