# Stubs for django.contrib.flatpages.templatetags.flatpages (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
import template

register = ...  # type: Any

class FlatpageNode(template.Node):
    context_name = ...  # type: Any
    starts_with = ...  # type: Any
    user = ...  # type: Any
    def __init__(self, context_name, starts_with: Optional[Any] = ..., user: Optional[Any] = ...) -> None: ...
    def render(self, context): ...

def get_flatpages(parser, token): ...
