# Stubs for django.contrib.messages.storage.cookie (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import json
from django.contrib.messages.storage.base import BaseStorage

class MessageEncoder(json.JSONEncoder):
    message_key = ...  # type: str
    def default(self, obj): ...

class MessageDecoder(json.JSONDecoder):
    def process_messages(self, obj): ...
    def decode(self, s, **kwargs): ...

class CookieStorage(BaseStorage):
    cookie_name = ...  # type: str
    max_cookie_size = ...  # type: int
    not_finished = ...  # type: str
