# Stubs for django.contrib.messages.storage.fallback (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.contrib.messages.storage.base import BaseStorage

class FallbackStorage(BaseStorage):
    storage_classes = ...  # type: Any
    storages = ...  # type: Any
    def __init__(self, *args, **kwargs) -> None: ...
