# Stubs for django.contrib.auth.migrations.0007_alter_validators_add_error_messages (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import migrations

class Migration(migrations.Migration):
    dependencies = ...  # type: Any
    operations = ...  # type: Any
