# Stubs for django.core.checks.templates (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

E001 = ...  # type: Any

def check_setting_app_dirs_loaders(app_configs, **kwargs): ...
