# Stubs for django.contrib.postgres.aggregates.general (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.models.aggregates import Aggregate

class ArrayAgg(Aggregate):
    function = ...  # type: str
    def convert_value(self, value, expression, connection, context): ...

class BitAnd(Aggregate):
    function = ...  # type: str

class BitOr(Aggregate):
    function = ...  # type: str

class BoolAnd(Aggregate):
    function = ...  # type: str

class BoolOr(Aggregate):
    function = ...  # type: str

class StringAgg(Aggregate):
    function = ...  # type: str
    template = ...  # type: str
    def __init__(self, expression, delimiter, **extra) -> None: ...
    def convert_value(self, value, expression, connection, context): ...
