# Stubs for django.contrib.postgres.aggregates.statistics (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from django.db.models.aggregates import Aggregate

class StatAggregate(Aggregate):
    x = ...  # type: Any
    y = ...  # type: Any
    source_expressions = ...  # type: Any
    def __init__(self, y, x, output_field: Any = ...) -> None: ...
    def get_source_expressions(self): ...
    def set_source_expressions(self, exprs): ...
    def resolve_expression(self, query: Optional[Any] = ..., allow_joins: bool = ..., reuse: Optional[Any] = ..., summarize: bool = ..., for_save: bool = ...): ...

class Corr(StatAggregate):
    function = ...  # type: str

class CovarPop(StatAggregate):
    function = ...  # type: Any
    def __init__(self, y, x, sample: bool = ...) -> None: ...

class RegrAvgX(StatAggregate):
    function = ...  # type: str

class RegrAvgY(StatAggregate):
    function = ...  # type: str

class RegrCount(StatAggregate):
    function = ...  # type: str
    def __init__(self, y, x) -> None: ...
    def convert_value(self, value, expression, connection, context): ...

class RegrIntercept(StatAggregate):
    function = ...  # type: str

class RegrR2(StatAggregate):
    function = ...  # type: str

class RegrSlope(StatAggregate):
    function = ...  # type: str

class RegrSXX(StatAggregate):
    function = ...  # type: str

class RegrSXY(StatAggregate):
    function = ...  # type: str

class RegrSYY(StatAggregate):
    function = ...  # type: str
