# Stubs for django.contrib.sessions.models (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.contrib.sessions.base_session import AbstractBaseSession, BaseSessionManager
import AbstractBaseSession

class SessionManager(BaseSessionManager):
    use_in_migrations = ...  # type: bool

class Session(AbstractBaseSession):
    objects = ...  # type: Any
    @classmethod
    def get_session_store_class(cls): ...
    class Meta(AbstractBaseSession.Meta):
        db_table = ...  # type: str
