# Stubs for django.db.backends.mysql.features (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.db.backends.base.features import BaseDatabaseFeatures
from .base import Database as Database

pytz = ...  # type: Any

class DatabaseFeatures(BaseDatabaseFeatures):
    empty_fetchmany_value = ...  # type: Any
    update_can_self_select = ...  # type: bool
    allows_group_by_pk = ...  # type: bool
    related_fields_match_type = ...  # type: bool
    allow_sliced_subqueries = ...  # type: bool
    has_bulk_insert = ...  # type: bool
    has_select_for_update = ...  # type: bool
    has_select_for_update_nowait = ...  # type: bool
    supports_forward_references = ...  # type: bool
    supports_regex_backreferencing = ...  # type: bool
    supports_date_lookup_using_string = ...  # type: bool
    can_introspect_autofield = ...  # type: bool
    can_introspect_binary_field = ...  # type: bool
    can_introspect_small_integer_field = ...  # type: bool
    supports_timezones = ...  # type: bool
    requires_explicit_null_ordering_when_grouping = ...  # type: bool
    allows_auto_pk_0 = ...  # type: bool
    uses_savepoints = ...  # type: bool
    can_release_savepoints = ...  # type: bool
    atomic_transactions = ...  # type: bool
    supports_column_check_constraints = ...  # type: bool
    can_clone_databases = ...  # type: bool
    def can_introspect_foreign_keys(self): ...
    def supports_microsecond_precision(self): ...
    def has_zoneinfo_database(self): ...
    def introspected_boolean_field_type(self, *args, **kwargs): ...
