# Stubs for django.contrib.gis.db.models.sql (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.contrib.gis.db.models.sql.conversion import AreaField as AreaField, DistanceField as DistanceField, GeomField as GeomField, GMLField as GMLField
