# Stubs for django.contrib.gis.db.models (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.models import *
from django.contrib.gis.db.models.aggregates import *
