# Stubs for django.contrib.gis.db.models.aggregates (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from django.db.models.aggregates import Aggregate

class GeoAggregate(Aggregate):
    function = ...  # type: Any
    is_extent = ...  # type: bool
    def as_sql(self, compiler, connection): ...
    tolerance = ...  # type: float
    template = ...  # type: str
    def as_oracle(self, compiler, connection): ...
    def resolve_expression(self, query: Optional[Any] = ..., allow_joins: bool = ..., reuse: Optional[Any] = ..., summarize: bool = ..., for_save: bool = ...): ...
    def convert_value(self, value, expression, connection, context): ...

class Collect(GeoAggregate):
    name = ...  # type: str

class Extent(GeoAggregate):
    name = ...  # type: str
    is_extent = ...  # type: str
    def __init__(self, expression, **extra) -> None: ...
    def convert_value(self, value, expression, connection, context): ...

class Extent3D(GeoAggregate):
    name = ...  # type: str
    is_extent = ...  # type: str
    def __init__(self, expression, **extra) -> None: ...
    def convert_value(self, value, expression, connection, context): ...

class MakeLine(GeoAggregate):
    name = ...  # type: str

class Union(GeoAggregate):
    name = ...  # type: str
