# Stubs for django.contrib.gis.db.models.manager (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class GeoManager:
    use_for_related_fields = ...  # type: bool
    def __init__(self, *args, **kwargs) -> None: ...
