# Stubs for django.contrib.gis.db.models.proxy (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

class SpatialProxy:
    def __init__(self, klass, field) -> None: ...
    def __get__(self, obj, type: Optional[Any] = ...): ...
    def __set__(self, obj, value): ...
