# Stubs for django.contrib.auth.admin (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
import admin
from django.utils.translation import ugettext_lazy as _

csrf_protect_m = ...  # type: Any
sensitive_post_parameters_m = ...  # type: Any

class GroupAdmin(admin.ModelAdmin):
    search_fields = ...  # type: Any
    ordering = ...  # type: Any
    filter_horizontal = ...  # type: Any
    def formfield_for_manytomany(self, db_field, request: Optional[Any] = ..., **kwargs): ...

class UserAdmin(admin.ModelAdmin):
    add_form_template = ...  # type: str
    change_user_password_template = ...  # type: Any
    fieldsets = ...  # type: Any
    add_fieldsets = ...  # type: Any
    form = ...  # type: Any
    add_form = ...  # type: Any
    change_password_form = ...  # type: Any
    list_display = ...  # type: Any
    list_filter = ...  # type: Any
    search_fields = ...  # type: Any
    ordering = ...  # type: Any
    filter_horizontal = ...  # type: Any
    def get_fieldsets(self, request, obj: Optional[Any] = ...): ...
    def get_form(self, request, obj: Optional[Any] = ..., **kwargs): ...
    def get_urls(self): ...
    def lookup_allowed(self, lookup, value): ...
    def add_view(self, request, form_url: str = ..., extra_context: Optional[Any] = ...): ...
    def user_change_password(self, request, id, form_url: str = ...): ...
    def response_add(self, request, obj, post_url_continue: Optional[Any] = ...): ...
