# Stubs for django.contrib.auth.middleware (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def get_user(request): ...

class AuthenticationMiddleware:
    def process_request(self, request): ...

class SessionAuthenticationMiddleware:
    def process_request(self, request): ...

class RemoteUserMiddleware:
    header = ...  # type: str
    force_logout_if_no_header = ...  # type: bool
    def process_request(self, request): ...
    def clean_username(self, username, request): ...

class PersistentRemoteUserMiddleware(RemoteUserMiddleware):
    force_logout_if_no_header = ...  # type: bool
