# Stubs for django.db.backends.postgresql.schema (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.backends.base.schema import BaseDatabaseSchemaEditor

class DatabaseSchemaEditor(BaseDatabaseSchemaEditor):
    sql_alter_column_type = ...  # type: str
    sql_create_sequence = ...  # type: str
    sql_delete_sequence = ...  # type: str
    sql_set_sequence_max = ...  # type: str
    sql_create_varchar_index = ...  # type: str
    sql_create_text_index = ...  # type: str
    def quote_value(self, value): ...
    def add_field(self, model, field): ...
