# Stubs for django.core.checks.security.csrf (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

W003 = ...  # type: Any
W016 = ...  # type: Any
W017 = ...  # type: Any

def check_csrf_middleware(app_configs, **kwargs): ...
def check_csrf_cookie_secure(app_configs, **kwargs): ...
def check_csrf_cookie_httponly(app_configs, **kwargs): ...
