# Stubs for django.contrib.admin.templatetags.log (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import template

register = ...  # type: Any

class AdminLogNode(template.Node):
    def __init__(self, limit, varname, user) -> None: ...
    def render(self, context): ...

def get_admin_log(parser, token): ...
