# Stubs for django.contrib.gis.db.backends.spatialite.base (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.db.backends.sqlite3.base import DatabaseWrapper as SQLiteDatabaseWrapper
from .client import SpatiaLiteClient as SpatiaLiteClient
from .features import DatabaseFeatures as DatabaseFeatures
from .introspection import SpatiaLiteIntrospection as SpatiaLiteIntrospection
from .operations import SpatiaLiteOperations as SpatiaLiteOperations
from .schema import SpatialiteSchemaEditor as SpatialiteSchemaEditor

class DatabaseWrapper(SQLiteDatabaseWrapper):
    SchemaEditorClass = ...  # type: Any
    spatialite_lib = ...  # type: Any
    features = ...  # type: Any
    ops = ...  # type: Any
    client = ...  # type: Any
    introspection = ...  # type: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def get_new_connection(self, conn_params): ...
    def prepare_database(self): ...
