# Stubs for django.contrib.gis.db.backends.spatialite.features (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.contrib.gis.db.backends.base.features import BaseSpatialFeatures
from django.db.backends.sqlite3.features import DatabaseFeatures as SQLiteDatabaseFeatures

class DatabaseFeatures(BaseSpatialFeatures, SQLiteDatabaseFeatures):
    supports_distance_geodetic = ...  # type: bool
    supports_num_points_poly = ...  # type: bool
    def supports_initspatialmetadata_in_one_transaction(self): ...
    def supports_3d_storage(self): ...
