# Stubs for django.contrib.gis.db.backends.spatialite.models (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import models
from django.contrib.gis.db.backends.base.models import SpatialRefSysMixin

class SpatialiteGeometryColumns(models.Model):
    f_table_name = ...  # type: Any
    f_geometry_column = ...  # type: Any
    coord_dimension = ...  # type: Any
    srid = ...  # type: Any
    spatial_index_enabled = ...  # type: Any
    class Meta:
        app_label = ...  # type: str
        db_table = ...  # type: str
        managed = ...  # type: bool
    @classmethod
    def table_name_col(cls): ...
    @classmethod
    def geom_col_name(cls): ...

class SpatialiteSpatialRefSys(models.Model, SpatialRefSysMixin):
    srid = ...  # type: Any
    auth_name = ...  # type: Any
    auth_srid = ...  # type: Any
    ref_sys_name = ...  # type: Any
    proj4text = ...  # type: Any
    @property
    def wkt(self): ...
    class Meta:
        app_label = ...  # type: str
        db_table = ...  # type: str
        managed = ...  # type: bool

def add_spatial_version_related_fields(sender, **kwargs): ...
