# Stubs for django.db.migrations.recorder (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from .exceptions import MigrationSchemaMissing as MigrationSchemaMissing
import models

class MigrationRecorder:
    class Migration(models.Model):
        app = ...  # type: Any
        name = ...  # type: Any
        applied = ...  # type: Any
        class Meta:
            apps = ...  # type: Any
            app_label = ...  # type: str
            db_table = ...  # type: str
    connection = ...  # type: Any
    def __init__(self, connection) -> None: ...
    @property
    def migration_qs(self): ...
    def ensure_schema(self): ...
    def applied_migrations(self): ...
    def record_applied(self, app, name): ...
    def record_unapplied(self, app, name): ...
    def flush(self): ...
