# Stubs for django.contrib.contenttypes.migrations.0002_remove_content_type_name (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import migrations

def add_legacy_name(apps, schema_editor): ...

class Migration(migrations.Migration):
    dependencies = ...  # type: Any
    operations = ...  # type: Any
