# Stubs for django.contrib.staticfiles.urls (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

urlpatterns = ...  # type: Any

def staticfiles_urlpatterns(prefix: Optional[Any] = ...): ...
