# Stubs for django.contrib.gis.db.backends.postgis.models (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import models
from django.contrib.gis.db.backends.base.models import SpatialRefSysMixin

class PostGISGeometryColumns(models.Model):
    f_table_catalog = ...  # type: Any
    f_table_schema = ...  # type: Any
    f_table_name = ...  # type: Any
    f_geometry_column = ...  # type: Any
    coord_dimension = ...  # type: Any
    srid = ...  # type: Any
    type = ...  # type: Any
    class Meta:
        app_label = ...  # type: str
        db_table = ...  # type: str
        managed = ...  # type: bool
    @classmethod
    def table_name_col(cls): ...
    @classmethod
    def geom_col_name(cls): ...

class PostGISSpatialRefSys(models.Model, SpatialRefSysMixin):
    srid = ...  # type: Any
    auth_name = ...  # type: Any
    auth_srid = ...  # type: Any
    srtext = ...  # type: Any
    proj4text = ...  # type: Any
    class Meta:
        app_label = ...  # type: str
        db_table = ...  # type: str
        managed = ...  # type: bool
    @property
    def wkt(self): ...
    @classmethod
    def wkt_col(cls): ...
