# Stubs for django.contrib.gis.db.backends.postgis.schema (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.db.backends.postgresql.schema import DatabaseSchemaEditor

class PostGISSchemaEditor(DatabaseSchemaEditor):
    geom_index_type = ...  # type: str
    geom_index_ops_nd = ...  # type: str
    rast_index_wrapper = ...  # type: str
    sql_add_spatial_index = ...  # type: str
    sql_clear_geometry_columns = ...  # type: str
    geometry_sql = ...  # type: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def geo_quote_name(self, name): ...
    def column_sql(self, model, field, include_default: bool = ...): ...
    def create_model(self, model): ...
    def delete_model(self, model): ...
    def add_field(self, model, field): ...
