# Stubs for django.core.management.commands.makemigrations (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.core.management.base import BaseCommand

class Command(BaseCommand):
    help = ...  # type: str
    def add_arguments(self, parser): ...
    verbosity = ...  # type: Any
    interactive = ...  # type: Any
    dry_run = ...  # type: Any
    merge = ...  # type: Any
    empty = ...  # type: Any
    migration_name = ...  # type: Any
    exit_code = ...  # type: Any
    def handle(self, *app_labels, **options): ...
    def write_migration_files(self, changes): ...
    def handle_merge(self, loader, conflicts): ...
