# Stubs for django.core.management.commands.showmigrations (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from django.core.management.base import BaseCommand

class Command(BaseCommand):
    help = ...  # type: str
    def add_arguments(self, parser): ...
    verbosity = ...  # type: Any
    def handle(self, *args, **options): ...
    def show_list(self, connection, app_names: Optional[Any] = ...): ...
    def show_plan(self, connection): ...
