# Stubs for django.core.management.commands.squashmigrations (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.core.management.base import BaseCommand

class Command(BaseCommand):
    help = ...  # type: str
    def add_arguments(self, parser): ...
    verbosity = ...  # type: Any
    interactive = ...  # type: Any
    def handle(self, **options): ...
    def find_migration(self, loader, app_label, name): ...
