# Stubs for django.contrib.gis.admin.widgets (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from django.forms.widgets import Textarea

geo_context = ...  # type: Any
logger = ...  # type: Any

class OpenLayersWidget(Textarea):
    def render(self, name, value, attrs: Optional[Any] = ...): ...
    def map_options(self): ...
