# Stubs for django.contrib.postgres.forms.hstore (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import forms
from django.utils.translation import ugettext_lazy as _

class HStoreField(forms.CharField):
    widget = ...  # type: Any
    default_error_messages = ...  # type: Any
    def prepare_value(self, value): ...
    def to_python(self, value): ...
    def has_changed(self, initial, data): ...
