# Stubs for django.contrib.postgres.forms.jsonb (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import six
import forms
from django.utils.translation import ugettext_lazy as _

class InvalidJSONInput(six.text_type): ...

class JSONField(forms.CharField):
    default_error_messages = ...  # type: Any
    def __init__(self, **kwargs) -> None: ...
    def to_python(self, value): ...
    def bound_data(self, data, initial): ...
    def prepare_value(self, value): ...
