# Stubs for django.contrib.postgres.forms.ranges (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
import forms
from django.forms.widgets import MultiWidget
from django.utils.translation import ugettext_lazy as _

class BaseRangeField(forms.MultiValueField):
    default_error_messages = ...  # type: Any
    def __init__(self, **kwargs) -> None: ...
    def prepare_value(self, value): ...
    def compress(self, values): ...

class IntegerRangeField(BaseRangeField):
    default_error_messages = ...  # type: Any
    base_field = ...  # type: Any
    range_type = ...  # type: Any

class FloatRangeField(BaseRangeField):
    default_error_messages = ...  # type: Any
    base_field = ...  # type: Any
    range_type = ...  # type: Any

class DateTimeRangeField(BaseRangeField):
    default_error_messages = ...  # type: Any
    base_field = ...  # type: Any
    range_type = ...  # type: Any

class DateRangeField(BaseRangeField):
    default_error_messages = ...  # type: Any
    base_field = ...  # type: Any
    range_type = ...  # type: Any

class RangeWidget(MultiWidget):
    def __init__(self, base_widget, attrs: Optional[Any] = ...) -> None: ...
    def decompress(self, value): ...
