# Stubs for django.contrib.contenttypes.admin (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from django.contrib.admin.checks import InlineModelAdminChecks
from django.contrib.admin.options import InlineModelAdmin

class GenericInlineModelAdminChecks(InlineModelAdminChecks): ...

class GenericInlineModelAdmin(InlineModelAdmin):
    ct_field = ...  # type: str
    ct_fk_field = ...  # type: str
    formset = ...  # type: Any
    checks_class = ...  # type: Any
    def get_formset(self, request, obj: Optional[Any] = ..., **kwargs): ...

class GenericStackedInline(GenericInlineModelAdmin):
    template = ...  # type: str

class GenericTabularInline(GenericInlineModelAdmin):
    template = ...  # type: str
