# Stubs for django.contrib.contenttypes.forms (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from django.forms.models import BaseModelFormSet

class BaseGenericInlineFormSet(BaseModelFormSet):
    instance = ...  # type: Any
    rel_name = ...  # type: Any
    def __init__(self, data: Optional[Any] = ..., files: Optional[Any] = ..., instance: Optional[Any] = ..., save_as_new: Optional[Any] = ..., prefix: Optional[Any] = ..., queryset: Optional[Any] = ..., **kwargs) -> None: ...
    @classmethod
    def get_default_prefix(cls): ...
    def save_new(self, form, commit: bool = ...): ...

def generic_inlineformset_factory(model, form: Any = ..., formset: Any = ..., ct_field: str = ..., fk_field: str = ..., fields: Optional[Any] = ..., exclude: Optional[Any] = ..., extra: int = ..., can_order: bool = ..., can_delete: bool = ..., max_num: Optional[Any] = ..., formfield_callback: Optional[Any] = ..., validate_max: bool = ..., for_concrete_model: bool = ..., min_num: Optional[Any] = ..., validate_min: bool = ...): ...
