# Stubs for django.contrib.contenttypes.views (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.utils.translation import ugettext as _

def shortcut(request, content_type_id, object_id): ...
